### ISSUE TITLE
Functionality of prohibited days

### ISSUE THREAD

**Issue by lachtanek** [yykamei/block-merge-based-on-time#1486]
Hello, I've found a discrepancy between how `prohibited-days-dates` works and what it says in the documentation:
- Documentation mentions "The comma-separated days or dates to stop blocking merge for all day."
- But the way it works is that it *blocks* merge for all day

This looks to be the offending condition: https://github.com/yykamei/block-merge-based-on-time/blob/main/src/should-block.ts#L9-L11
Now, I am not sure what was the original intention, but it feels to me like the only reasonable course now is to change the docs and leave the functionality, just not to break existing apps.
But the functionality of allowing merge for all day seems to be useful at least to how our team works (our engineering team is located in different country to where our clients are), so maybe a separate setting for this would be cool.

Might open a PR with this too, once I have a bit more free time.

Cheers!

**Comment by yykamei** [comment]
Thank you for reporting the issue! You're absolutely right. The README.md is wrong, and the explanation should be "The comma-separated days or dates to block merge for all day." Do you plan to open a pull request?
