### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by sszemeresky** [yykamei/block-merge-based-on-time#1736]
Error: Unhandled error: GraphqlResponseError: Request failed due to following response errors:
 - Resource not accessible by integration

getting the above error while integrating the action. what's the graphql your requesting?

**Comment by yykamei** [comment]
Hi @sszemeresky,

Thank you for reporting the issue. I'm also encountering this issue. Maybe, specifying `permissions` in your workflow would resolve this problem. Would you try this configuration?

https://github.com/yykamei/block-merge-based-on-time?tab=readme-ov-file#usage

<img width="480" alt="Screenshot 2024-08-04 at 22 53 46" src="https://github.com/user-attachments/assets/cc2b2eb7-89b0-4561-9c14-fa20cf2d51ee">

**Comment by sszemeresky** [comment]
getting two errors now

Error: Unhandled error: GraphqlResponseError: Request failed due to following response errors:
 - Resource not accessible by integration
 - Resource not accessible by integration

**Comment by yykamei** [comment]
OK, thank you for reporting. I want to see the detailed log by [enabling debug mode](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging). Would you mind giving me the debug log?

By the way, I forgot to answer your first question.

> getting the above error while integrating the action. what's the graphql your requesting?

You can see what queries this action sends to GitHub.

https://github.com/yykamei/block-merge-based-on-time/blob/b1ff83334834ea3a76d311be080af0183d9775a5/src/github.ts

**Comment by sszemeresky** [comment]
unfortunately i'm unable to turn debug mode on

**Comment by yykamei** [comment]
Thank you for your patience. I understand that enabling debug mode is not an option for you. Could you please share any additional logs or information you have that might help me diagnose the issue? It would also be helpful to know more about your environment and the specific steps you took when encountering the error. Plus, I want to know whether [this](https://github.com/yykamei/block-merge-based-on-time/issues/1736#issuecomment-2267552284) change works or not.

**Comment by sszemeresky** [comment]
>I want to know whether [this](https://github.com/yykamei/block-merge-based-on-time/issues/1736#issuecomment-2267552284) change works or not.

unfortunately permissions didn't help

**Comment by yykamei** [comment]
Thank you for the update. OK, could you provide any additional details about your environment and the specific steps that lead to the error? Any extra information would help in diagnosing the issue.

**Comment by sszemeresky** [comment]
i just made a pull request adding this workflow
`name: Block Merge Based on Time
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: '*/30 * * * *'

jobs:
  block:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - uses: yykamei/block-merge-based-on-time@main
        id: block
        with:
          timezone: UTC+2
          after: '16:00'
          before: '07:00'
          base-branches: '(default)'
          prohibited-days-dates: 'Friday, Saturday, Sunday, H:Poland, BH:Poland'
      - run: echo pr-blocked=${{ steps.block.outputs.pr-blocked }}
        if: github.event_name == 'pull_request'`

**Comment by yykamei** [comment]
@sszemeresky 

Thank you for giving me your workflow file. Thank to that, I found out `contents: read` is also required to successfully run this workflow. Please try to add this permission in your file!

**Comment by sszemeresky** [comment]
adding contents: read permission worked! thx! could add this to your readme ;)

**Comment by yykamei** [comment]
Thank you! I added this via https://github.com/yykamei/block-merge-based-on-time/commit/7bff24c92bd4f38a513384ff7cfc242a3578442b, so I close this issue. I appreciate you opened this issue 😄
