### ISSUE TITLE
Support for multiple no-block labels

### ISSUE THREAD

**Issue by slavab89** [yykamei/block-merge-based-on-time#1793]
We have a use-case where we would like to use multiple labels, all of which indicating a "no-block".
Some of those labels trigger other actions.

Would it be possible to add this functionality?
Do you think it will be viable to use the same input as `no-block-label` even though it might accept a comma separated string and not only a single one?

**Comment by yykamei** [comment]
Thank you for opening the issue! 😄 

That's interesting. You want to prevent this GitHub Action from blocking pull requests with multiple labels, don't you? For example, you have the following pull requests and want to circumvent the block for pull request 1 and pull request 2.

* pull request 1, which has the "no-block" and "maintenance" labels.
* pull request 2, which has the "stop-blocking" label.
* pull request 3, which has the "feature" and "epi-228" labels.

In this case, Block Merge Based on Time should support multiple values in `no-block-label` like this:

```yaml
with:
  no-block-label: no-block, stop-blocking
```

I think it makes sense to support multiple labels for `no-block-label`, but I want to know the motivation. Why can't the pull request 2 be labeled with "no-block"?

Thanks,

**Comment by slavab89** [comment]
The use case that we have is that we're sending a notification (Through a different Github Action) when someone wants to merge a PR outside of working hours. However, this notification and blocking does not apply for everyone.
It is based on either who created the PR or which files were changed as part of this. Both those cases might be resolved through looking into the `pull_request` event data, but they are not applicable for the `schedule` part.

To put it into more specific usecase:
block-merge-based-on-time is set as a required status check for PRs via a RuleSet
- pull request 1 - has changed special file A -> block based on time, unless add a label of "special-merge" -> Will trigger a notification if "special-merge" label exists during merge
- pull request 2 - Was opened by person B -> no need to block based on time, ignore the hours check

In order to go around the required block-merge-based-on-time status check and to mark it as "ok", we were thinking on adding a different label "allow-merge" to pull request 2. This label, however, will NOT trigger the notification (like in pull request 1)

We're aware that we're unable to enforce who can use which label, but that's a different issue.

**Comment by yykamei** [comment]
Thank you for explaining your context! It makes sense to me. OK, let's try to support multiple labels. As far as I know, [`inputs`](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#inputs) supports only String so far, so I think `no-block-label` should handle comma-separated string like this.

```yaml
with:
  no-block-label: no-block, stop-blocking
```

Do you want to try it? If you are busy, I will implement it.

**Comment by yykamei** [comment]
Thank you for opening the pull request! I merged it. I will check it in my environment and release a new version after that. If you want to use this feature soon, please use `main` tag in your workflow like this.

```yaml
    steps:
      - uses: yykamei/block-merge-based-on-time@main
```

**Comment by slavab89** [comment]
Thanks a lot
This action greatly helps us
